In [1]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch import Tensor, cat, sigmoid
from torch.autograd import Variable
import numpy as np

In [2]:
class XOR_brain(nn.Module):

    def __init__(self, lrate, loss_fn, in_size, out_size):
        super(XOR_brain, self).__init__()

        self.loss_fn = loss_fn

        self.fc1_in = nn.Linear(in_size, 2)
        self.fc2_out = nn.Linear(2, out_size)

        self.optimizer = optim.SGD(self.parameters(), lr=lrate, momentum=0.9)

    def forward(self, x):
        x = sigmoid(self.fc1_in(x))
        x = self.fc2_out(x)
        return x

    def step(self, x, y):
        
        self.optimizer.zero_grad()
        y_hat = self(x)
        loss = self.loss_fn.forward(y_hat, y)

        # Optimize based on gradient from loss function
        
        loss.backward()
        self.optimizer.step()
        
        return loss.data.numpy()

In [3]:
brain = XOR_brain(0.02, nn.MSELoss(), 2, 1)

In [4]:
def weights_init(model):
    for m in model.modules():
        if isinstance(m, nn.Linear):
            # initialize the weight tensor, here we use a normal distribution
            m.weight.data.normal_(0, 1)

weights_init(brain)

In [5]:
X = Tensor([[0,0],[0,1], [1,0], [1,1]])
Y = Tensor([0,1,1,0]).view(-1,1)

In [6]:
epochs = 8000
for i in range(epochs):
    data_point = np.random.randint(X.size(0))
    x_var = Variable(X[data_point], requires_grad=False)
    y_var = Variable(Y[data_point], requires_grad=False)

    loss = brain.step(x_var, y_var)
        
    if i % 500 == 0:
        print( "Epoch: {0}, Loss: {1}, ".format(i, loss) )

Epoch: 0, Loss: 2.402541160583496, 
Epoch: 500, Loss: 0.03145718201994896, 
Epoch: 1000, Loss: 0.07714302092790604, 
Epoch: 1500, Loss: 0.46755585074424744, 
Epoch: 2000, Loss: 0.37772035598754883, 
Epoch: 2500, Loss: 0.15895988047122955, 
Epoch: 3000, Loss: 0.3838280141353607, 
Epoch: 3500, Loss: 0.40384793281555176, 
Epoch: 4000, Loss: 0.010504873469471931, 
Epoch: 4500, Loss: 9.387588761455845e-06, 
Epoch: 5000, Loss: 5.184261908652843e-08, 
Epoch: 5500, Loss: 6.87805368215777e-12, 
Epoch: 6000, Loss: 5.684341886080802e-14, 
Epoch: 6500, Loss: 2.2737367544323206e-13, 
Epoch: 7000, Loss: 2.2737367544323206e-13, 
Epoch: 7500, Loss: 5.684341886080802e-14, 


In [74]:
X[0]

tensor([0., 0.])

In [7]:
brain(X[0])

tensor([0.], grad_fn=<AddBackward0>)

In [8]:
brain(X[1])

tensor([1.0000], grad_fn=<AddBackward0>)

In [9]:
brain(X[2])

tensor([1.0000], grad_fn=<AddBackward0>)

In [12]:
brain(X[3])

tensor([4.7684e-07], grad_fn=<AddBackward0>)

In [13]:
X3 = Tensor([[0,0,0],[0,0,1], [0,1,0], [0,1,1],[1,0,0],[1,0,1], [1,1,0], [1,1,1]])
Y3 = Tensor([0,1,1,0,1,0,0,1]).view(-1,1)

In [18]:
brain3 = XOR_brain(0.02, nn.MSELoss(), 3, 1)
weights_init(brain3)

In [19]:
epochs = 12001
for i in range(epochs):
    data_point = np.random.randint(X3.size(0))
    x_var = Variable(X3[data_point], requires_grad=False)
    y_var = Variable(Y3[data_point], requires_grad=False)

    loss = brain3.step(x_var, y_var)
        
    if i % 2000 == 0:
        print( "Epoch: {0}, Loss: {1}, ".format(i, loss) )

Epoch: 0, Loss: 0.9962866306304932, 
Epoch: 2000, Loss: 0.3642100989818573, 
Epoch: 4000, Loss: 0.30818209052085876, 
Epoch: 6000, Loss: 0.46041634678840637, 
Epoch: 8000, Loss: 0.972288966178894, 
Epoch: 10000, Loss: 0.014242002740502357, 
Epoch: 12000, Loss: 0.008652811869978905, 


In [21]:
brain3(X3[0])

tensor([-0.0608], grad_fn=<AddBackward0>)

In [31]:
for i in range(X3.size(0)):
    print(brain3(X3[i]), Y3[i])

tensor([-0.0608], grad_fn=<AddBackward0>) tensor([0.])
tensor([0.8134], grad_fn=<AddBackward0>) tensor([1.])
tensor([0.7759], grad_fn=<AddBackward0>) tensor([1.])
tensor([0.0259], grad_fn=<AddBackward0>) tensor([0.])
tensor([0.7627], grad_fn=<AddBackward0>) tensor([1.])
tensor([0.0258], grad_fn=<AddBackward0>) tensor([0.])
tensor([0.0244], grad_fn=<AddBackward0>) tensor([0.])
tensor([0.0054], grad_fn=<AddBackward0>) tensor([1.])
